[package]
name = "leaflet-core"
version.workspace = true
edition = "2024"
authors.workspace = true
repository.workspace = true

[dependencies]
anyhow = { workspace = true }
chrono = "0.4.42"
sysinfo = "0.37.2"
thiserror = "2.0.17"
tokio = { workspace = true }
