[package]
name = "leaflet-cli"
version = "0.1.0"
edition = "2024"

[dependencies]
ratatui = "0.29.0"
anyhow = { workspace = true }
tokio = { workspace = true }
clap = { version = "4.5.50", features = ["derive"] }
leaflet-core = { path = '../leaflet-core' }
